/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface FractiveProject {
  /**
   * The game title that will be shown to players
   */
  title?: string;
  /**
   * The author name that will be shown to players
   */
  author?: string;
  /**
   * The long-form game description that will be shown to players
   */
  description?: string;
  /**
   * A web URL that will be shown to players
   */
  website?: string;
  /**
   * List of files and/or folders where Markdown source files reside. These are compiled in the order in which they appear. Folders are searched recursively for files with a .md extension.
   */
  markdown?: string[];
  /**
   * List of files and/or folders where Javascript files reside. These are imported in the order in which they appear. Folders are searched recursively for files with a .js extension.
   */
  javascript?: string[];
  /**
   * List of files and/or folders where additional asset files reside. These are imported in the order in which they appear. Folders are searched recursively for all files.
   */
  assets?: string[];
  /**
   * The HTML template file to use for the final story output
   */
  template?: string;
  /**
   * The folder where the final story files will be saved
   */
  output?: string;
  /**
   * If true, report all build steps as normal but don't actually modify any files on disk
   */
  dryRun?: boolean;
  /**
   * If true, minify the final story HTML (reduces file size but makes the HTML source much less human-readable)
   */
  minify?: boolean;
}
